### ISSUE TITLE
Prediction using NEI

### ISSUE THREAD

**Issue by zhanxw** [PATRIC3/mic_prediction#2]
Hello, 

This command line crash: `bash mic_prediction_fasta.sh test_fasta/1001.fasta temp/ data_files/NEI.model.pkl 1 test_out/xgbGenomeTest data_files/NEI.ArrInds data_files/antibioticsList_NEI.uniq data_files/NEI_MICMethods data_files/all_kmrs`

Error message:

```
Traceback (most recent call last):
  File "/qbrc/home/zhanxw/software/mic_prediction/makeMatrix.py", line 53, in <module>
    kmcLine += featureHash[i] + ':' + kmcContigs[i] + ' '
KeyError: 'AAACAGGCCT'
Traceback (most recent call last):
  File "/qbrc/home/zhanxw/software/mic_prediction/testXGBoost.py", line 22, in <module>
    dtest = xgb.DMatrix(argv[2])
  File "/qbrc/home/zhanxw/software/xgboost/python-package/xgboost/core.py", line 393, in __init__
    ctypes.byref(self.handle)))
  File "/qbrc/home/zhanxw/software/xgboost/python-package/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [17:08:32] src/io/input_split_base.cc:173: Check failed: files_.size() != 0U (0 vs. 0) Cannot find any files that matches the URI pattern temp/1001.fasta.libsvm
```

Is the NEI model usable? I hope to get MIC values as specified in the file `data_files/NEI_MICMethods`.

**Comment by Tinyman392** [comment]
The error looks like it stems from the fact that none of our genomes that were used in training/testing/validation had the 10mer _AAACAGGCCT_.  I have updated the makeMatrix.py file to deal with this issue.  The NEI model is useable, that particular 10mer (and its count) will have no bearing on the prediction made since none of our genomes used to train the model contain that 10mer.
